project:
  type: website
lang: pt
website:
  title: ""
  navbar:
    right:
      - text: Início
        href: index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/cmusso86
      - icon: linkedin
        href: https://twitter.com
format:
  html:
    theme: minty
    css: styles.css

editor: visual

